### ISSUE TITLE
Latest MantisAPI release doesn't link with gcc

### ISSUE THREAD

**Issue by bmaione** [Aqueti/mantis_examples#11]
When trying to compile a C/C++ script with gcc using -lMantisAPI gcc cannot find the library.

/usr/lib/gcc/x86_64-linux-gnu/5/../../../../lib/libMantisAPI.so: file not recognized: File truncated
collect2: error: ld returned 1 exit status

**Comment by bmaione** [comment]
0.1.2.3 does not have this issue. 0.1.2.4 does.

**Comment by sfeller** [comment]
@camerongivler once again, I believe you have already fixed this. @bmaione, can you verify if this is complete?

**Comment by bmaione** [comment]
GCC now links with the latest download of mantisapi (0.1.2.4)

**Comment by bmaione** [comment]
This has not been fixed. Here is the error I get.

usr/lib/gcc/x86_64-linux-gnu/5/../../../../lib/libMantisAPI.so: file not recognized: File truncated

**Comment by sfeller** [comment]
That's very ugly. The ../../../.. stuff implies we are not correctly referencing the libraries.

**Comment by camerongivler** [comment]
Looking into it...

**Comment by camerongivler** [comment]
Made a few changes.  Compiles on my system referencing libMantisAPI.so installed at the system level.

**Comment by camerongivler** [comment]
Please close if this works for you @bmaione

**Comment by bmaione** [comment]
Mantisapi (0.1.3.0) in alpha release on office 365 compiles. Mantisapi (0.1.2.4) in the development folder does not. I assume, development hasn't had a new package recently. Please confirm @camerongivler

**Comment by camerongivler** [comment]
That's correct.  Development will be updated almost daily and will be ahead again today, but if alpha works for you, then we can close this issue.

**Comment by sfeller** [comment]
Use the alpha release for now. If you need functionality in the development release, let us know and we will have Alex verify functionality and upgrade that to alpha.



Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10
