### ISSUE TITLE
saveMcamFrame causes a seg fault ~50% of the time

### ISSUE THREAD

**Issue by bmaione** [Aqueti/mantis_examples#12]
In the Mantis C api saving an Mcam frame using the function saveMcamFrame causes a seg fault maybe every other operation. Requesting the most recent frame doesn't seem to cause it to faullt.

**Comment by sfeller** [comment]
@camerongivler I believe you looked into this yesterday. If not, I believe this is something you will need to look at.

**Comment by camerongivler** [comment]
I have not looked into this, but will make it a priority

**Comment by bmaione** [comment]
According to @bjschwa2, this was fixed in the latest API release (the one that didn't compile).

**Comment by bjschwarz** [comment]
@bmaione could you verify if this is still an issue?

**Comment by sfeller** [comment]
Please include the version info provided with the -h option to make sure we know what version the issue comes from.

**Comment by uberferg** [comment]
@bmaione can you post the code that is causing the seg fault? I can't seem to reproduce this error without passing the saveMCamFrame method a NULL image buffer in the FRAME struct.

Aside: @sfeller should we perform a NULL pointer check on the image buffer of the FRAME struct given to the saveMCamFrame function, or should it be the user's responsibilty to check that they are giving the method a valid FRAME struct?

**Comment by sfeller** [comment]
We should check for a null frame and generate the appropriate message. Developers may not be experts, especially for the python api

Sent using OWA for iPhone
________________________________

**Comment by sfeller** [comment]
@bmaione is this the issue we fixed today? I doubt it's the same, but could be.

**Comment by bmaione** [comment]
Not the same issue. I haven't had a chance, (or a need to rather) to verify saving capability through a the mantis API.

**Comment by uberferg** [comment]
Added checks to saveMCamFrame that:
1. Check m_image buffer for nullptr
2. Check file name char* for nullptr
3. Check allocated CamImage size to prevent segfault when writing

@bmaione can you check if this fixed the issue for and close if it's resolved? I haven't been seeing the seg fault to begin with, so I can't verify myself that this changed anything.
