### ISSUE TITLE
setMCamWhiteBalance uses R, B, G

### ISSUE THREAD

**Issue by smccain** [Aqueti/mantis_examples#13]
The setMCamWhiteBalance mode 3 doubles to set the manual white balance (R, B, G)

getMCamWhiteBalance uses a AtlWhiteBalance datatype. It would seem to be better to be consistent and use the AtlWhiteBalance datatype for both

**Comment by bjschwarz** [comment]
This has been fixed in the current master branch. Camviewer has also been updated to use the new API function.
