### ISSUE TITLE
Examples link to system API rather than compiled API

### ISSUE THREAD

**Issue by bmaione** [Aqueti/mantis_examples#15]

**Comment by camerongivler** [comment]
fixed in commit aqueti/acos@ebd4f4e9fe394965f02807a4a43875f186cb5395

@bmaione if the setup I described to you with a separate repository for compiling against system libraries vs compiled works, please close this issue.

**Comment by bjschwarz** [comment]
Examples might link but Applications does not. Applications requires a system installed API when compiled in ACOS.

**Comment by camerongivler** [comment]
please check this again @bjschwa2 I might have fixed it

**Comment by camerongivler** [comment]
The true fix for this is going to CMake Config files rather than FindXXX.cmake files.  Lowering priority, because this seems to be solved for the short-term, but this should not be our long-term system.

**Comment by sfeller** [comment]
Shouldn't mantis_examples always link to the system API? If we use a compiled API, perhaps it belongs in applications. This will allow the mantis_examples to server as example code for customers that do not have access to the internal repositories.

**Comment by camerongivler** [comment]
No it should not.  If it is compiled as part of ACOS, it should link to the compiled ACOS.

**Comment by sfeller** [comment]
I'm fine with this as long as there is no specific reference to the acos repository in the mantis_examples code.
