### ISSUE TITLE
Evetar_AutoFocus cause V2 to crash

### ISSUE THREAD

**Issue by yuanxy92** [Aqueti/mantis_examples#16]
I installed opencv3.2 and compiled Evetar_AutoFocus successfully.

However, running Evetar_AutoFocus will cause V2 to crash. Besides, it often encounters JSON parsing error:
`ERROR: JsonServer could not parse message
Invalid character found: '1'
ERROR(client process): Invalid version.  Missing message or sourceId:{
	"message" : {
		"ATL_WHITEBALANCE" : {
			"stateType" : "property",
			"type" : "AtlWhiteBalanceState",
			"value" : {
				"blue" : null
			}
		}
	},
	"sourceId" : null
}
`
output of Evetar_AutoFocus:

[run3.txt](https://github.com/Aqueti/mantis_examples/files/1043614/run3.txt)

**Comment by yuanxy92** [comment]
Sorry, I ran the code on a non evetar camera this morning. I will try this on another camera later.

**Comment by camerongivler** [comment]
@bmaione do you see this?

**Comment by bmaione** [comment]
I haven't tried running V2 and the focus script at the same time. Since the focus script uses the microcamera API i'm not sure why it would cause a crash, unless there is some weird port issue going on.

**Comment by bmaione** [comment]
It appears that I fixed this with most recent mantis examples commit. Closing for now.

**Comment by smccain** [comment]
We tried this on a camera we retro-fitted with all Evetar sensors and it works well with V2 running in parallel.

**Comment by smccain** [comment]
With the Evetar sensors you can use Evetar_AutoFocus to autofocus all cameras in parallel.
With the Leopard or Evetar sensors you can use Mantis_Camera_Focus to fine tune focusing with a graphical overlay to better determine best focus position
