### ISSUE TITLE
Problem running V2

### ISSUE THREAD

**Issue by whyuan1221** [Aqueti/mantis_examples#5]
1. I updated acos, camviewer, agt, and mantisapi:

acos-0.2.0.5_dev.deb
agt-0.2.1.1_dev.deb
camviewer-0.1.1.1_dev.deb
mantisapi-0.1.2.1_dev.deb

2. Then I ran start.sh:

ssh ubuntu@10.0.2.1 "ps aux | grep acos |grep -v grep"
ubuntu    2778  128  3.2 7145868 131352 ?      Sl   06:28   0:03 acosd
ssh ubuntu@10.0.2.2 "ps aux | grep acos |grep -v grep"
ubuntu    2771  107  3.2 7159132 133424 ?      Sl   06:28   0:04 acosd
ssh ubuntu@10.0.2.3 "ps aux | grep acos |grep -v grep"
ubuntu    2769  100  3.2 7145900 133632 ?      Sl   06:28   0:05 acosd
ssh ubuntu@10.0.2.4 "ps aux | grep acos |grep -v grep"
ubuntu    2767  117  3.3 7147052 138488 ?      Sl   06:28   0:05 acosd
ssh ubuntu@10.0.2.5 "ps aux | grep acos |grep -v grep"
ubuntu    2714  112  3.5 7145900 145636 ?      Sl   06:28   0:06 acosd
ssh ubuntu@10.0.2.6 "ps aux | grep acos |grep -v grep"
ubuntu    2728  127  3.4 7145932 140344 ?      Sl   06:28   0:07 acosd
ssh ubuntu@10.0.2.7 "ps aux | grep acos |grep -v grep"
ubuntu    2747  140  2.6 7103924 109108 ?      Sl   06:28   0:09 acosd
ssh ubuntu@10.0.2.8 "ps aux | grep acos |grep -v grep"
ubuntu    2747  127  3.6 7149692 149680 ?      Sl   06:28   0:08 acosd
ssh ubuntu@10.0.2.9 "ps aux | grep acos |grep -v grep"
ubuntu    2725  124  3.4 7145868 140024 ?      Sl   06:28   0:09 acosd
ssh ubuntu@10.0.2.10 "ps aux | grep acos |grep -v grep"
ubuntu    2848 94.0  2.3 6651160 96288 ?       Sl   06:28   0:08 acosd

Then ./V2 

===============================================
    Welcome to V2, the Aqueti Visual Cortex
===============================================
Command server listening on port 9999
using .//camera_1181053543
Command server listening on port 10000
Command server listening on port 10001
Command server listening on port 10002
Command server listening on port 10003
Command server listening on port 10004
Command server listening on port 10005
Command server listening on port 10006
Command server listening on port 10007
Command server listening on port 10008
Command server listening on port 10009
Command server listening on port 10010
Command server listening on port 10011
Command server listening on port 10012
Command server listening on port 10013
Command server listening on port 10014

Microcamera metrics:
	Currently receiving data: false
	mcam 1031700042: 	received: 0	   added: 0
	mcam 1031700043: 	received: 0	   added: 0
	mcam 1031700044: 	received: 0	   added: 0
	mcam 1031700045: 	received: 0	   added: 0
	mcam 1031700046: 	received: 0	   added: 0
	mcam 1031700047: 	received: 0	   added: 0
	mcam 1031700048: 	received: 0	   added: 0
	mcam 1031700049: 	received: 0	   added: 0
	mcam 1031700050: 	received: 0	   added: 0
	mcam 1031700051: 	received: 0	   added: 0
	mcam 1031700052: 	received: 0	   added: 0
	mcam 1031700053: 	received: 0	   added: 0
	mcam 1031700054: 	received: 0	   added: 0
	mcam 1031700055: 	received: 0	   added: 0
	mcam 1031700056: 	received: 0	   added: 0
	mcam 1031700057: 	received: 0	   added: 0
	mcam 1031700058: 	received: 0	   added: 0
	mcam 1031700059: 	received: 0	   added: 0
	mcam 1031700060: 	received: 0	   added: 0

Microcamera metrics:
	Currently receiving data: false
	mcam 1031700042: 	received: 0	   added: 0
	mcam 1031700043: 	received: 0	   added: 0
	mcam 1031700044: 	received: 0	   added: 0
	mcam 1031700045: 	received: 0	   added: 0
	mcam 1031700046: 	received: 0	   added: 0
	mcam 1031700047: 	received: 0	   added: 0
	mcam 1031700048: 	received: 0	   added: 0
	mcam 1031700049: 	received: 0	   added: 0
	mcam 1031700050: 	received: 0	   added: 0
	mcam 1031700051: 	received: 0	   added: 0
	mcam 1031700052: 	received: 0	   added: 0
	mcam 1031700053: 	received: 0	   added: 0
	mcam 1031700054: 	received: 0	   added: 0
	mcam 1031700055: 	received: 0	   added: 0
	mcam 1031700056: 	received: 0	   added: 0
	mcam 1031700057: 	received: 0	   added: 0
	mcam 1031700058: 	received: 0	   added: 0
	mcam 1031700059: 	received: 0	   added: 0
	mcam 1031700060: 	received: 0	   added: 0

Then ./Nous:

Corrupt JPEG data: premature end of data segment
Corrupt JPEG data: premature end of data segment
Corrupt JPEG data: premature end of data segment
Corrupt JPEG data: premature end of data segment
Corrupt JPEG data: premature end of data segment
Corrupt JPEG data: premature end of data segment
Corrupt JPEG data: premature end of data segment
Corrupt JPEG data: premature end of data segment
Corrupt JPEG data: premature end of data segment
Corrupt JPEG data: premature end of data segment
Corrupt JPEG data: premature end of data segment
Corrupt JPEG data: premature end of data segment
Corrupt JPEG data: premature end of data segment
Corrupt JPEG data: premature end of data segment
Corrupt JPEG data: premature end of data segment
Corrupt JPEG data: premature end of data segment
Corrupt JPEG data: premature end of data segment
Corrupt JPEG data: premature end of data segment
Corrupt JPEG data: premature end of data segment
Corrupt JPEG data: premature end of data segment
Corrupt JPEG data: premature end of data segment
Corrupt JPEG data: premature end of data segment
Corrupt JPEG data: premature end of data segment
Corrupt JPEG data: premature end of data segment

From nohup:

ERROR: ArgusConsumerBase.cpp::mainLoop: 226: new frame time should be greater than previous max time. max time: 1394222970704277248 timestamp: 1493793203571429

ERROR: 

ERROR: 

ERROR: ArgusConsumerBase.cpp::mainLoop: 226: new frame time should be greater than previous max time. max time: 1394222970709726720 timestamp: 1493793203570252

ERROR: 

ERROR: ArgusConsumerBase.cpp::mainLoop: 226: new frame time should be greater than previous max time. max time: 1394222970709713664 timestamp: 1493793203573733

ERROR: 

ERROR: ArgusConsumerBase.cpp::mainLoop: 226: new frame time should be greater than previous max time. max time: 1394222970704252928 timestamp: 1493793203605318

ERROR: 

ERROR: ArgusConsumerBase.cpp::mainLoop: 226: new frame time should be greater than previous max time. max time: 1394222970742930176 timestamp: 1493793203604744

ERROR: 

ERROR: ArgusConsumerBase.cpp::mainLoop: 226: new frame time should be greater than previous max time. max time: 1394222970704277248 timestamp: 1493793203604419

And nohup report after I ran Nous, we can stream live video through nous:

INFO: DataTransmitter.cpp::operator():146: Stopping streaming to 10.0.2.220:9002 from 1031700046

INFO: DataTransmitter.cpp::operator():131: Starting streaming to 10.0.2.220:9002 from 1031700047

INFO: DataTransmitter.cpp::operator():146: Stopping streaming to 10.0.2.220:9002 from 1031700047

INFO: DataTransmitter.cpp::operator():38: Received add connection interrupt from 10.0.2.220:9002

INFO: DataTransmitter.cpp::addConnection:104: Connecting to 10.0.2.220:9002

Command server listening on port 10010
INFO: DataTransmitter.cpp::operator():131: Starting streaming to 10.0.2.220:9002 from 1031700048

INFO: DataTransmitter.cpp::operator():164: Setting tiling filter for 10.0.2.220:9002 to 2

INFO: DataTransmitter.cpp::operator():146: Stopping streaming to 10.0.2.220:9002 from 1031700048

INFO: DataTransmitter.cpp::operator():131: Starting streaming to 10.0.2.220:9002 from 1031700048

INFO: DataTransmitter.cpp::operator():146: Stopping streaming to 10.0.2.220:9002 from 1031700048

INFO: DataTransmitter.cpp::operator():131: Starting streaming to 10.0.2.220:9002 from 1031700047

INFO: DataTransmitter.cpp::operator():131: Starting streaming to 10.0.2.220:9002 from 1031700048

INFO: DataTransmitter.cpp::operator():146: Stopping streaming to 10.0.2.220:9002 from 1031700047

INFO: DataTransmitter.cpp::operator():146: Stopping streaming to 10.0.2.220:9002 from 1031700048

INFO: DataTransmitter.cpp::operator():131: Starting streaming to 10.0.2.220:9002 from 1031700049

INFO: DataTransmitter.cpp::operator():146: Stopping streaming to 10.0.2.220:9002 from 1031700049

INFO: DataTransmitter.cpp::operator():131: Starting streaming to 10.0.2.220:9002 from 1031700049

INFO: DataTransmitter.cpp::operator():146: Stopping streaming to 10.0.2.220:9002 from 1031700049

INFO: DataTransmitter.cpp::operator():131: Starting streaming to 10.0.2.220:9002 from 1031700048

INFO: DataTransmitter.cpp::operator():146: Stopping streaming to 10.0.2.220:9002 from 1031700048

INFO: DataTransmitter.cpp::operator():131: Starting streaming to 10.0.2.220:9002 from 1031700046

INFO: DataTransmitter.cpp::operator():146: Stopping streaming to 10.0.2.220:9002 from 1031700046

INFO: DataTransmitter.cpp::operator():131: Starting streaming to 10.0.2.220:9002 from 1031700047

INFO: DataTransmitter.cpp::operator():131: Starting streaming to 10.0.2.220:9002 from 1031700048

INFO: DataTransmitter.cpp::operator():146: Stopping streaming to 10.0.2.220:9002 from 1031700047

INFO: DataTransmitter.cpp::operator():146: Stopping streaming to 10.0.2.220:9002 from 1031700048

INFO: DataTransmitter.cpp::operator():131: Starting streaming to 10.0.2.220:9002 from 1031700049

INFO: DataTransmitter.cpp::operator():146: Stopping streaming to 10.0.2.220:9002 from 1031700049

INFO: DataTransmitter.cpp::operator():131: Starting streaming to 10.0.2.220:9002 from 1031700050

/home/ubuntu/bin/moveFocusMotor.py 1 50 &
im initializing here
['1', '50']
I will move motor 1 50 steps forward
im initializing here
setting sec per step at 0.003
Double coil steps
0.003  sec per step
/home/ubuntu/bin/moveFocusMotor.py 1 50 &
im initializing here
['1', '50']
I will move motor 1 50 steps forward
im initializing here
setting sec per step at 0.003
Double coil steps
0.003  sec per step
/home/ubuntu/bin/moveFocusMotor.py 1 50 &
im initializing here
['1', '50']
I will move motor 1 50 steps forward
im initializing here
setting sec per step at 0.003
Double coil steps
0.003  sec per step
/home/ubuntu/bin/moveFocusMotor.py 1 50 &
im initializing here
['1', '50']
I will move motor 1 50 steps forward
im initializing here
setting sec per step at 0.003
Double coil steps
0.003  sec per step
/home/ubuntu/bin/moveFocusMotor.py 1 50 &
im initializing here
['1', '50']
I will move motor 1 50 steps forward
im initializing here
setting sec per step at 0.003
Double coil steps
0.003  sec per step
/home/ubuntu/bin/moveFocusMotor.py 1 50 &
im initializing here
['1', '50']
I will move motor 1 50 steps forward
im initializing here
setting sec per step at 0.003
Double coil steps
0.003  sec per step
/home/ubuntu/bin/moveFocusMotor.py 1 50 &
im initializing here
['1', '50']
I will move motor 1 50 steps forward
im initializing here
setting sec per step at 0.003
Double coil steps
0.003  sec per step
INFO: DataTransmitter.cpp::operator():146: Stopping streaming to 10.0.2.220:9002 from 1031700050

INFO: DataTransmitter.cpp::operator():131: Starting streaming to 10.0.2.220:9002 from 1031700051

/home/ubuntu/bin/moveFocusMotor.py 2 50 &
im initializing here
['2', '50']
I will move motor 2 50 steps forward
im initializing here
setting sec per step at 0.003
Double coil steps
0.003  sec per step
/home/ubuntu/bin/moveFocusMotor.py 2 50 &
im initializing here
['2', '50']
I will move motor 2 50 steps forward
im initializing here
setting sec per step at 0.003
Double coil steps
0.003  sec per step
/home/ubuntu/bin/moveFocusMotor.py 2 50 &
im initializing here
['2', '50']
I will move motor 2 50 steps forward
im initializing here
setting sec per step at 0.003
Double coil steps
0.003  sec per step
/home/ubuntu/bin/moveFocusMotor.py 2 50 &
im initializing here
['2', '50']
I will move motor 2 50 steps forward
im initializing here
setting sec per step at 0.003
Double coil steps
0.003  sec per step
INFO: DataTransmitter.cpp::operator():146: Stopping streaming to 10.0.2.220:9002 from 1031700051

INFO: DataTransmitter.cpp::operator():131: Starting streaming to 10.0.2.220:9002 from 1031700052

INFO: DataTransmitter.cpp::operator():146: Stopping streaming to 10.0.2.220:9002 from 1031700052

INFO: DataTransmitter.cpp::operator():131: Starting streaming to 10.0.2.220:9002 from 1031700052

/home/ubuntu/bin/moveFocusMotor.py 1 50 &
im initializing here
['1', '50']
I will move motor 1 50 steps forward
im initializing here
setting sec per step at 0.003
Double coil steps
0.003  sec per step
INFO: DataTransmitter.cpp::operator():146: Stopping streaming to 10.0.2.220:9002 from 1031700052

INFO: DataTransmitter.cpp::operator():131: Starting streaming to 10.0.2.220:9002 from 1031700052

INFO: DataTransmitter.cpp::operator():146: Stopping streaming to 10.0.2.220:9002 from 1031700052

INFO: DataTransmitter.cpp::operator():131: Starting streaming to 10.0.2.220:9002 from 1031700052

/home/ubuntu/bin/moveFocusMotor.py 1 50 &
im initializing here
['1', '50']
I will move motor 1 50 steps forward
im initializing here
setting sec per step at 0.003
Double coil steps
0.003  sec per step
/home/ubuntu/bin/moveFocusMotor.py 1 50 &
im initializing here
['1', '50']
I will move motor 1 50 steps forward
im initializing here
setting sec per step at 0.003
Double coil steps
0.003  sec per step
INFO: DataTransmitter.cpp::operator():146: Stopping streaming to 10.0.2.220:9002 from 1031700052

INFO: DataTransmitter.cpp::operator():131: Starting streaming to 10.0.2.220:9002 from 1031700053

/home/ubuntu/bin/moveFocusMotor.py 2 50 &
im initializing here
['2', '50']
I will move motor 2 50 steps forward
im initializing here
setting sec per step at 0.003
Double coil steps
0.003  sec per step
/home/ubuntu/bin/moveFocusMotor.py 2 50 &
im initializing here
['2', '50']
I will move motor 2 50 steps forward
im initializing here
setting sec per step at 0.003
Double coil steps
0.003  sec per step
/home/ubuntu/bin/moveFocusMotor.py 2 50 &
im initializing here
['2', '50']
I will move motor 2 50 steps forward
im initializing here
setting sec per step at 0.003
Double coil steps
0.003  sec per step

**Comment by camerongivler** [comment]
I believe this issue is resolved, correct?
