### ISSUE TITLE
"saveMCamFrame" calls Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by anl13** [Aqueti/mantis_examples#8]
I copy the sample code "MantisGetFrames.c" to "test_getFrame.c" (which is still the same to sample code), compile it and run it, then it calls `Segmentation fault(Core dumped)`. I run sample `MantisGetFrames` and get the same error. I use VisualStudioCode to debug it, find that it fails at function `saveMCamFrame`, which calls an error:
```
Error: Unable to open 'memcpy-avx-unaligned.S':File not found(/build/glibc-9tT8Do/glibc-2.23/sysdeps/x86_64/multiarch/memcpy-avx-unaligned.S). 
```
All output of `test_getFrame` (same to MantisGetFrames`) is shown below: 
```Shell
ubuntu@ubuntu-Mantis2-Render:~/mantis_cam2/scripts$ ./test_getFrame 
Virtual camera 1181053543 now receiving data from its 19 mcams
API found microcamera 1031700044 at 10.0.2.2:9999 for camera 1181053543
API found microcamera 1031700045 at 10.0.2.2:9999 for camera 1181053543
API found microcamera 1031700050 at 10.0.2.5:9999 for camera 1181053543
API found microcamera 1031700051 at 10.0.2.5:9999 for camera 1181053543
API found microcamera 1031700060 at 10.0.2.10:9999 for camera 1181053543
API found microcamera 1031700056 at 10.0.2.8:9999 for camera 1181053543
API found microcamera 1031700057 at 10.0.2.8:9999 for camera 1181053543
API found microcamera 1031700048 at 10.0.2.4:9999 for camera 1181053543
API found microcamera 1031700049 at 10.0.2.4:9999 for camera 1181053543
API found microcamera 1031700054 at 10.0.2.7:9999 for camera 1181053543
API found microcamera 1031700055 at 10.0.2.7:9999 for camera 1181053543
API found microcamera 1031700046 at 10.0.2.3:9999 for camera 1181053543
API found microcamera 1031700047 at 10.0.2.3:9999 for camera 1181053543
API found microcamera 1031700042 at 10.0.2.1:9999 for camera 1181053543
API found microcamera 1031700043 at 10.0.2.1:9999 for camera 1181053543
API found microcamera 1031700052 at 10.0.2.6:9999 for camera 1181053543
API found microcamera 1031700053 at 10.0.2.6:9999 for camera 1181053543
API found microcamera 1031700058 at 10.0.2.9:9999 for camera 1181053543
API found microcamera 1031700059 at 10.0.2.9:9999 for camera 1181053543
getFrame 1031700044
Saved frame data/mcam_1031700044 to disk
Returned the pointer for the frame buffer
getFrame 1031700045
Saved frame data/mcam_1031700045 to disk
Returned the pointer for the frame buffer
getFrame 1031700050
Saved frame data/mcam_1031700050 to disk
Returned the pointer for the frame buffer
getFrame 1031700051
Saved frame data/mcam_1031700051 to disk
Returned the pointer for the frame buffer
getFrame 1031700060
Segmentation fault (core dumped)
```
I run it several times, it always fails, but they fail at different `MCamID`. It seems that it fails randomly. 
**Question:** Why the `Segmentation fault` arises? How to fix it?

**Comment by camerongivler** [comment]
Wow this is a crazy one. @uberferg and @bjschwa2 we should test this and run it in valgrind to make sure there are no weird memory errors.

**Comment by uberferg** [comment]
This was occurring due to an invalid image pointer returned from getFrame when the request fails (a.k.a. when the requested image was not found). The invalid pointer was not being set to NULL, but was also not a valid pointer, and so passing this invalid frame into saveMCamFrame caused the memcpy to seg fault when reading from the invalid buffer pointer. 

Now the image pointer of getFrame is explicitly set to NULL when the request fails, and this can be used to reliably check if the image is valid before passing it into saveMCamFrame. To validate, I ran the example "MantisGetFrames.c" 100 times and it never seg faulted.

The fix will be in tonight's release. Please validate the fix and close the issue if it works.
