### ISSUE TITLE
MantisRecord Frame request failed!

### ISSUE THREAD

**Issue by yuanxy92** [Aqueti/mantis_examples#9]
I tested this example on two cameras in kunshan lab. One seems OK (I am not very sure, and Kevin has taken the camera to Anhui for demo, so I can not test the camera now.)

The other one has problem, and the output is as follows:

_API connected to 1 Mantis systems
Virtual camera 1181053543 already receiving data from its 19 mcams
New clip callback registered with the API
Started recording a clip
Stopped recording the clip
New clip callback received a new clip named 2017-05-03_08:37:34AM
A new clip (4.953844 seconds) has been created with name 2017-05-03_08:37:34AM
Requesting frames for clip 2017-05-03_08:37:34AM on camera 1181053543 from 19 microcameras
Sending frame request 0
Frame request failed!
Sending frame request 1
Frame request failed!
Sending frame request 2
Frame request failed!_

About 20G data is written into the disk with large numbers of .hc files. I update the output log and the example data here.

[mantisrecord_log2.txt](https://github.com/Aqueti/mantis_examples/files/976181/mantisrecord_log2.txt)

[example_data.tar.gz](https://github.com/Aqueti/mantis_examples/files/976185/example_data.tar.gz)

**Comment by camerongivler** [comment]
@uberferg may be able to shed some light on this

**Comment by camerongivler** [comment]
Can you post the code you're using?

**Comment by yuanxy92** [comment]
I use the code MantisRecord.c without any modification

**Comment by uberferg** [comment]
This was an issue with the way we established the start and end times of clips. We originally used the system clock time on the render machine, which only works if the time on the render machine is perfectly synced to the times on the Tegras. Now clip times are established using the frame timestamps from the start and end of the clip segment. This should fix the issue and allow the render system to have an arbitrary system clock relative to the camera system.

The fix will be in tonight's release. Please validate the changes and close the issue if it is fixed.
